const DATA_URL='CONTROLE%20DE%20ABASTECIMENTO%20-%20POSTO%20COSTALOG%20-%20INTERNO%20-%2028042025.csv.zip';
const PASS={admin:'6414b877f3b53d65c4a4596d3eed8b6b7532e971a1b8bc3a05024f53dafcbef8',user:'b8fa4b66429e97aaf969dd5aca1d931b38f341911bd33c5ee91f492da4ae235e'};
let allRows=[],filteredRows=[],currentPage=1,pageSize=20;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function num(v){v=String(v??'').trim();if(!v)return 0;if(v.includes(','))return parseFloat(v.replace(/\./g,'').replace(',','.'))||0;return parseFloat(v)||0}
function csv(t){let sep=(t.split(/\r?\n/)[0].split(';').length>t.split(/\r?\n/)[0].split(',').length)?';':',';let a=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x==='"'){if(q&&n==='"'){c+='"';i++}else q=!q}else if(x===sep&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;r.push(c);if(r.some(Boolean))a.push(r);r=[];c=''}else c+=x}if(c||r.length){r.push(c);a.push(r)}return a}
function normalize(a){let h=a[0];return a.slice(1).map((r,i)=>{let o={id:i+1};h.forEach((k,j)=>o[k]=(r[j]??'').trim());o.liters=num(o['Qtd - Litros']);o.odo=num(o['Hodômetro']);o.date=o.DATA||'';o.time=o.HORA||'';o.employee=(o['FUNCIONÁRIO']||'').trim().toUpperCase();o.plate=(o.Placa||'').trim().toUpperCase().replace(/[ -]/g,'');o.photoPlate=o['Foto- Placa']||o['Foto - Placa']||o['Foto-Placa']||'';o.photoOdo=o['foto - Hodômetro']||o['Foto - Hodômetro']||o['Foto-Hodômetro']||'';o.photoPump=o['Foto - bomba']||o['Foto-bomba']||o['Foto - Bomba']||'';return o}).filter(x=>x.plate)}
function fmt(n,d=0){return new Intl.NumberFormat('pt-BR',{maximumFractionDigits:d}).format(n)}
function br(d){if(!d)return'—';let p=d.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:d}
function dt(o){return br(o.date)+' '+(o.time||'')}
async function sha(s){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function load(){try{const r=await fetch(DATA_URL+'?v=20261007',{cache:'no-store'});if(!r.ok)throw Error('Arquivo ZIP não encontrado ('+r.status+')');const zip=await JSZip.loadAsync(await r.arrayBuffer());const files=Object.keys(zip.files).filter(k=>/\.csv$/i.test(k)&&!zip.files[k].dir);if(!files.length)throw Error('CSV não encontrado no ZIP');const textCsv=await zip.files[files[0]].async('string');allRows=normalize(csv(textCsv));const local=JSON.parse(localStorage.getItem('costalogAbastecimentos')||'[]');allRows.push(...local.map((x,i)=>({...x,id:'local-'+i,plate:String(x.plate||x.Placa||'').toUpperCase().replace(/[ -]/g,'')})));renderAll();populateQuestionOptions();$('loading').classList.add('hidden')}catch(err){console.error('Erro ao carregar base:',err);$('loading').innerHTML='<strong>Não foi possível carregar a base.</strong><span>'+esc(err.message)+'</span><button class="secondary-btn" onclick="location.reload()">Tentar novamente</button>'}}
function renderAll(){renderSettings();renderQuestions()}
function stats(){let ls=allRows.reduce((a,r)=>a+r.liters,0),od=allRows.filter(r=>r.odo).map(r=>r.odo),dates=[...allRows].sort((a,b)=>a.date.localeCompare(b.date)),last=[...allRows].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0];$('statRecords').textContent=fmt(allRows.length);$('statLiters').textContent=fmt(ls,0)+' L';$('statVehicles').textContent=fmt(new Set(allRows.map(r=>r.plate)).size);$('statOdo').textContent=fmt(od.reduce((a,b)=>a+b,0)/(od.length||1),0)+' km';$('statLast').textContent=last?br(last.date):'—';$('periodLabel').textContent=dates.length?br(dates[0].date)+' — '+br(last.date):'—'}
function chart(){let m={};allRows.forEach(r=>{let k=r.date.slice(0,7);if(k)m[k]=(m[k]||0)+r.liters});let ks=Object.keys(m).sort().slice(-12),mx=Math.max(...ks.map(k=>m[k]),1);$('monthChart').innerHTML=ks.map(k=>{let [y,n]=k.split('-');let lab=new Date(+y,+n-1,1).toLocaleDateString('pt-BR',{month:'short'}).replace('.','');return '<div class="bar-item"><b>'+fmt(m[k],0)+' L</b><i style="height:'+Math.max(8,m[k]/mx*145)+'px"></i><small>'+lab+'</small></div>'}).join('')}
function alerts(){let a=allRows.filter(r=>!/Sim - ok/i.test(r['Possuí Antifurto?']||'')).length,t=allRows.filter(r=>!['1','2'].includes(r['Quantos tanque o veículo possui?'])).length,v=allRows.filter(r=>r.liters>800).length;$('alerts').innerHTML=[['⚠','Antifurto','Registros fora de “Sim - ok”',a],['!','Tanques','Respostas que precisam de conferência',t],['↗','Volume','Abastecimentos acima de 800 L',v]].map(x=>'<div class="alert-row"><b>'+x[0]+'</b><div><strong>'+x[1]+'</strong><span>'+x[2]+'</span></div><em>'+fmt(x[3])+'</em></div>').join('')}
function employees(){let m={};allRows.forEach(r=>{m[r.employee]??={n:0,l:0};m[r.employee].n++;m[r.employee].l+=r.liters});$('employeeRanking').innerHTML=Object.entries(m).sort((a,b)=>b[1].n-a[1].n).map(([n,v],i)=>'<div class="rank-row"><span class="rank">'+String(i+1).padStart(2,'0')+'</span><div class="rank-name"><strong>'+esc(n)+'</strong><span>'+fmt(v.l,0)+' L</span></div><div class="rank-count">'+fmt(v.n)+' registros</div></div>').join('')}
function recent(){let a=[...allRows].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,6);$('recentList').innerHTML=a.map(r=>'<div class="recent-row"><div class="plate">'+esc(r.plate)+'</div><div><strong>'+esc(r.employee)+'</strong><span>'+dt(r)+'</span></div><b>'+fmt(r.liters,2)+' L</b></div>').join('')}
function filters(){let e=[...new Set(allRows.map(r=>r.employee).filter(Boolean))].sort(),t=[...new Set(allRows.map(r=>r['Quantos tanque o veículo possui?']).filter(Boolean))].sort();$('employeeFilter').innerHTML='<option value="">Todos os funcionários</option>'+e.map(x=>'<option>'+esc(x)+'</option>').join('');$('tankFilter').innerHTML='<option value="">Todos os tanques</option>'+t.map(x=>'<option>'+esc(x)+'</option>').join('')}
function apply(){let q=$('searchInput').value.trim().toUpperCase(),e=$('employeeFilter').value,t=$('tankFilter').value,d=+$('dateFilter').value,min='';if(d){let x=new Date();x.setDate(x.getDate()-d);min=x.toISOString().slice(0,10)}filteredRows=allRows.filter(r=>(!q||r.plate.includes(q)||r.employee.includes(q))&&(!e||r.employee===e)&&(!t||r['Quantos tanque o veículo possui?']===t)&&(!min||r.date>=min)).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));currentPage=1;history()}
function history(){let s=(currentPage-1)*pageSize,a=filteredRows.slice(s,s+pageSize);$('historyBody').innerHTML=a.length?a.map(r=>'<tr><td>'+dt(r)+'</td><td><strong>'+esc(r.employee)+'</strong></td><td><span class="plate-chip">'+esc(r.plate)+'</span></td><td>'+fmt(r.odo)+' km</td><td><strong>'+fmt(r.liters,2)+' L</strong></td><td><span class="status-dot '+(/Sim - ok/i.test(r['Possuí Antifurto?'])?'ok':'warn')+'">'+esc(r['Possuí Antifurto?']||'—')+'</span></td><td>'+esc(r['Quantos tanque o veículo possui?']||'—')+'</td></tr>').join(''):'<tr><td colspan="7" class="no-results">Nenhum registro encontrado.</td></tr>';let p=Math.max(1,Math.ceil(filteredRows.length/pageSize));$('filterSummary').textContent=fmt(filteredRows.length)+' registros encontrados';$('pagination').innerHTML='<button '+(currentPage===1?'disabled':'')+' data-page="'+(currentPage-1)+'">‹</button><span>Página '+currentPage+' de '+p+'</span><button '+(currentPage===p?'disabled':'')+' data-page="'+(currentPage+1)+'">›</button>'}
function vehicles(){let q=($('vehicleSearch')?.value||'').toUpperCase(),m={};allRows.forEach(r=>{if(q&&!r.plate.includes(q))return;m[r.plate]??={n:0,l:0,odo:0,last:r};m[r.plate].n++;m[r.plate].l+=r.liters;m[r.plate].odo=Math.max(m[r.plate].odo,r.odo);if((r.date+r.time)>(m[r.plate].last.date+m[r.plate].last.time))m[r.plate].last=r});$('vehicleGrid').innerHTML=Object.entries(m).sort((a,b)=>b[1].l-a[1].l).slice(0,120).map(([p,v])=>'<article class="vehicle-card"><div class="vehicle-head"><span class="plate-chip">'+esc(p)+'</span><span>'+fmt(v.n)+' abastecimentos</span></div><strong>'+fmt(v.l,0)+' L</strong><div class="vehicle-meta"><span>Último: '+br(v.last.date)+'</span><span>Hod.: '+fmt(v.odo)+' km</span></div></article>').join('')}
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const target=$(v+'View');if(!target)return;target.classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='settings')renderSettings();if(v==='questions')renderQuestions();scrollTo({top:0,behavior:'smooth'})}
function modal(open){$('entryModal').classList.toggle('hidden',!open);if(open){let d=new Date();$('entryForm').reset();$('entryDate').value=d.toISOString().slice(0,10);$('entryTime').value=d.toTimeString().slice(0,5);populateQuestionOptions();updatePlateAutomation();updateOdoAutomation();updateLitersAutomation();['photoPlatePreview','photoOdoPreview','photoPumpPreview'].forEach(id=>{if($(id))$(id).innerHTML=''})}}
function save(e){e.preventDefault();const plate=($('entryPlate').value||'').toUpperCase().replace(/[ -]/g,'');$('entryPlate').value=plate;const employee=$('entryEmployee').value.trim().toUpperCase(),odo=+($('entryOdo').value||0),liters=+($('entryLiters').value||0),anti=$('entryAnti').value,tanks=$('entryTanks').value;if(!plate||plate.length<6||!employee||!$('entryDate').value||!odo||!liters||!anti||!tanks){showEntryValidation('Preencha todos os campos obrigatórios marcados com *.','error');return}const last=lastForPlate(plate);if(last&&odo<last.odo){showEntryValidation('O hodômetro não pode ser menor que o último registro desta placa ('+fmt(last.odo)+' km).','error');return}const o={'DATA':$('entryDate').value,'HORA':$('entryTime').value,'FUNCIONÁRIO':employee,'Placa':plate,'Qtd - Litros':String(liters),'Hodômetro':String(odo),'Possuí Antifurto?':anti,'Quantos tanque o veículo possui?':tanks,employee,plate,odo,liters,date:$('entryDate').value,time:$('entryTime').value,photoPlate:$('entryPhotoPlate').files?.[0]?.name||'',photoOdo:$('entryPhotoOdo').files?.[0]?.name||'',photoPump:$('entryPhotoPump').files?.[0]?.name||'',photoCount:[$('entryPhotoPlate').files?.[0],$('entryPhotoOdo').files?.[0],$('entryPhotoPump').files?.[0]].filter(Boolean).length};let arr=JSON.parse(localStorage.getItem('costalogAbastecimentos')||'[]');arr.push(o);localStorage.setItem('costalogAbastecimentos',JSON.stringify(arr));allRows.push({...o,id:'local-'+Date.now()});modal(false);renderAll();view('answers');alert('Abastecimento registrado com sucesso neste navegador.')}
async function login(e){e.preventDefault();let h=await sha($('accessPassword').value);if(h!==PASS.admin&&h!==PASS.user){$('loginError').textContent='Senha incorreta. Verifique os dados e tente novamente.';return}$('loginError').textContent='';sessionStorage.setItem('costalogAuth','1');$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');load().catch(err=>{$('loading').innerHTML='<strong>Não foi possível carregar a base.</strong><span>Confira o arquivo CSV no repositório.</span>';console.error(err)})}
function theme(){let d=localStorage.getItem('costalogTheme')==='dark';document.body.classList.toggle('dark-mode',d);const b=$('themeToggle');if(b)b.textContent=d?'☀':'☾';renderSettings?.()}
$('loginForm').addEventListener('submit',login);$('togglePassword').onclick=()=>{$('accessPassword').type=$('accessPassword').type==='password'?'text':'password'};$('logoutBtn').onclick=()=>{sessionStorage.removeItem('costalogAuth');location.reload()};$('themeToggle').onclick=()=>{localStorage.setItem('costalogTheme',document.body.classList.contains('dark-mode')?'light':'dark');theme()};
document.addEventListener('click',e=>{let v=e.target.closest('[data-view]');if(v)view(v.dataset.view);if(e.target.closest('[data-close]'))modal(false);if(e.target.closest('#newEntryBtn,#historyNewBtn'))modal(true);let p=e.target.closest('[data-page]');if(p&&!p.disabled){currentPage=+p.dataset.page;history()}});
$('entryForm').onsubmit=save;theme();
(function(){let c=$('matrixLayer'),x=c.getContext('2d'),w,h,d;function z(){w=c.width=innerWidth;h=c.height=innerHeight;d=Array(Math.ceil(w/18)).fill(1)}function f(){x.clearRect(0,0,w,h);x.fillStyle='rgba(0,0,0,.4)';x.font='12px monospace';d.forEach((y,i)=>{x.fillText(Math.random()>.5?'1':'0',i*18,y*18);if(y*18>h&&Math.random()>.975)d[i]=0;d[i]++});requestAnimationFrame(f)}z();addEventListener('resize',z);f()})();
theme();
if(sessionStorage.getItem('costalogAuth')){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');load().catch(console.error)}

/* Páginas complementares: Perguntas, Respostas e Configurações */
function renderQuestions(){const b=$('questionsNewBtn');if(b)b.onclick=()=>modal(true)}
function filteredAnswerRows(){
 const q=($('answerSearch')?.value||'').trim().toUpperCase();
 const from=$('answerDateFrom')?.value||'',to=$('answerDateTo')?.value||'',emp=$('answerEmployee')?.value||'',plate=$('answerPlate')?.value||'',anti=$('answerAnti')?.value||'';
 return allRows.filter(r=>{
   const hay=[r.date,r.time,r.employee,r.plate,String(r.liters),String(r.odo),r['Possuí Antifurto?'],r['Quantos tanque o veículo possui?']].join(' ').toUpperCase();
   return (!q||hay.includes(q))&&(!from||r.date>=from)&&(!to||r.date<=to)&&(!emp||r.employee===emp)&&(!plate||r.plate===plate)&&(!anti||r['Possuí Antifurto?']===anti);
 }).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));
}
function renderAnswerFilterOptions(){
 const es=[...new Set(allRows.map(r=>r.employee).filter(Boolean))].sort(),ps=[...new Set(allRows.map(r=>r.plate).filter(Boolean))].sort();
 if($('answerEmployee')){const v=$('answerEmployee').value;$('answerEmployee').innerHTML='<option value="">Todos os funcionários</option>'+es.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');$('answerEmployee').value=v}
 if($('answerPlate')){const v=$('answerPlate').value;$('answerPlate').innerHTML='<option value="">Todos os veículos</option>'+ps.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');$('answerPlate').value=v}
}
function renderAnswers(){
 if(!$('answersBody'))return;
 renderAnswerFilterOptions();
 const rows=filteredAnswerRows(),alerts=rows.filter(r=>!/Sim - ok/i.test(r['Possuí Antifurto?']||'')||r.liters>800).length;
 $('answerTotal').textContent=fmt(rows.length);$('answerLiters').textContent=fmt(rows.reduce((s,r)=>s+r.liters,0),2)+' L';$('answerVehicles').textContent=fmt(new Set(rows.map(r=>r.plate)).size);$('answerAlerts').textContent=fmt(alerts);
 $('answerFilterSummary').textContent=rows.length+' registro'+(rows.length===1?'':'s')+' encontrado'+(rows.length===1?'':'s');
 const body=rows.slice(0,500).map((r,i)=>{const photos=[r.photoPlate,r.photoOdo,r.photoPump].filter(Boolean).length;const alert=!/Sim - ok/i.test(r['Possuí Antifurto?']||'')||r.liters>800;return '<tr class="answer-row" data-answer-id="'+esc(String(r.id))+'"><td class="row-number">'+fmt(i+1)+'</td><td><strong>'+br(r.date)+'</strong></td><td>'+esc(r.time||'—')+'</td><td><strong>'+esc(r.employee||'—')+'</strong></td><td><span class="plate-chip">'+esc(r.plate||'—')+'</span></td><td><strong>'+fmt(r.liters,2)+' L</strong></td><td>'+fmt(r.odo)+' km</td><td><span class="status-dot '+(/Sim - ok/i.test(r['Possuí Antifurto?']||'')?'ok':'warn')+'">'+esc(r['Possuí Antifurto?']||'—')+'</span></td><td>'+esc(r['Quantos tanque o veículo possui?']||'—')+'</td><td>'+(photos?'<span class="evidence-badge">📷 '+photos+'</span>':'<span class="evidence-empty">—</span>')+(alert?'<span class="row-alert">!</span>':'')+'</td></tr>'}).join('');
 $('answersBody').innerHTML=body||'<tr><td colspan="10" class="no-results"><div>⌕</div><strong>Nenhuma resposta encontrada</strong><span>Tente remover algum filtro ou alterar a pesquisa.</span></td></tr>';
 $('answerLastUpdate').textContent='Base atualizada • '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
}
function showAnswerDetail(id){
 const r=allRows.find(x=>String(x.id)===String(id));if(!r)return;
 $('answerDetailTitle').textContent=(r.plate||'Abastecimento')+' • '+br(r.date);
 $('answerDetailSubtitle').textContent=(r.employee||'Funcionário não informado')+' • '+(r.time||'Horário não informado');
 const photos=[['Foto da placa',r.photoPlate],['Foto do hodômetro',r.photoOdo],['Foto da bomba',r.photoPump]];
 $('answerDetailBody').innerHTML='<div class="detail-summary"><div><small>DATA E HORA</small><strong>'+br(r.date)+' • '+esc(r.time||'—')+'</strong></div><div><small>FUNCIONÁRIO</small><strong>'+esc(r.employee||'—')+'</strong></div><div><small>PLACA</small><strong class="plate-chip">'+esc(r.plate||'—')+'</strong></div></div><div class="detail-grid"><div><span>Hodômetro</span><strong>'+fmt(r.odo)+' km</strong></div><div><span>Quantidade abastecida</span><strong>'+fmt(r.liters,2)+' L</strong></div><div><span>Antifurto</span><strong>'+esc(r['Possuí Antifurto?']||'—')+'</strong></div><div><span>Quantidade de tanques</span><strong>'+esc(r['Quantos tanque o veículo possui?']||'—')+'</strong></div></div><div class="detail-evidence"><h3>Evidências</h3><div class="evidence-grid">'+photos.map(([label,url])=>url?'<a class="evidence-card" href="'+esc(url)+'" target="_blank" rel="noopener"><span>📷</span><div><strong>'+label+'</strong><small>Ver evidência</small></div></a>':'<div class="evidence-card empty"><span>—</span><div><strong>'+label+'</strong><small>Não disponível</small></div></div>').join('')+'</div></div>';
 $('answerDetailModal').classList.remove('hidden');
}

function exportAnswers(){
 const rows=allRows.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));
 const head=['DATA','HORA','FUNCIONÁRIO','Placa','Qtd - Litros','Hodômetro','Possuí Antifurto?','Quantos tanque o veículo possui?','Foto - Placa','Foto - Hodômetro','Foto - bomba'];
 const csvRows=[head,...rows.map(r=>head.map(k=>String(r[k]??(k==='Foto - Placa'?r.photoPlate:k==='Foto - Hodômetro'?r.photoOdo:k==='Foto - bomba'?r.photoPump:'' )).replaceAll('"','""')))].map(r=>r.map(v=>'"'+v+'"').join(';')).join('\r\n');
 const blob=new Blob(['\\ufeff'+csvRows],{type:'text/csv;charset=utf-8;'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respostas-abastecimento-costalog.csv';a.click();URL.revokeObjectURL(a.href);
}
function lastForPlate(p){return [...allRows].filter(r=>r.plate===p).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]}
function populateQuestionOptions(){const es=[...new Set(allRows.map(r=>r.employee).filter(Boolean))].sort(),ps=[...new Set(allRows.map(r=>r.plate).filter(Boolean))].sort();if($('employeeOptions'))$('employeeOptions').innerHTML=es.map(x=>'<option value="'+esc(x)+'">').join('');if($('plateOptions'))$('plateOptions').innerHTML=ps.map(x=>'<option value="'+esc(x)+'">').join('')}
function showEntryValidation(msg,type='warn'){const b=$('entryValidation');if(!b)return;b.className='validation-box '+type;b.innerHTML=msg;b.classList.remove('hidden')}
function updatePlateAutomation(){const p=($('entryPlate')?.value||'').toUpperCase().replace(/[ -]/g,'');const f=$('plateFeedback'),r=lastForPlate(p);if(!f)return;if(!p){f.textContent='';return}if(r){f.className='field-feedback ok';f.textContent='✓ Veículo encontrado • último hodômetro: '+fmt(r.odo)+' km • '+br(r.date)}else{f.className='field-feedback';f.textContent='Novo veículo/placa. Confira a identificação.'}}
function updateOdoAutomation(){const p=($('entryPlate')?.value||'').toUpperCase().replace(/[ -]/g,''),v=+($('entryOdo')?.value||0),r=lastForPlate(p),f=$('odoFeedback');if(!f)return;if(r&&v<r.odo){f.className='field-feedback error';f.textContent='⚠ Menor que o último hodômetro: '+fmt(r.odo)+' km'}else if(r){f.className='field-feedback ok';f.textContent='✓ Hodômetro coerente com o histórico'}else{f.textContent=''}}
function updateLitersAutomation(){const v=+($('entryLiters')?.value||0),f=$('litersFeedback');if(!f)return;if(v>800){f.className='field-feedback warn';f.textContent='⚠ Volume acima de 800 L: será marcado para conferência'}else if(v){f.className='field-feedback ok';f.textContent='✓ '+fmt(v,2)+' L informado'}else f.textContent=''}
function previewPhoto(inputId,previewId){const i=$(inputId),p=$(previewId);if(!i||!p)return;i.addEventListener('change',()=>{p.innerHTML='';const file=i.files?.[0];if(!file)return;const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt='Pré-visualização';p.appendChild(img);const s=document.createElement('span');s.textContent=file.name;p.appendChild(s)})}
function setupExtraPages(){
 ['answerSearch','answerDateFrom','answerDateTo','answerEmployee','answerPlate','answerAnti'].forEach(id=>$(id)?.addEventListener('input',renderAnswers));
 $('refreshAnswers')?.addEventListener('click',renderAnswers);
 $('exportAnswersBtn')?.addEventListener('click',exportAnswers);
 $('clearAnswerFilters')?.addEventListener('click',()=>{['answerSearch','answerDateFrom','answerDateTo'].forEach(id=>{if($(id))$(id).value=''});['answerEmployee','answerPlate','answerAnti'].forEach(id=>{if($(id))$(id).value=''});renderAnswers()});
 $('answersBody')?.addEventListener('click',e=>{const row=e.target.closest('.answer-row');if(row)showAnswerDetail(row.dataset.answerId)});
 document.querySelectorAll('[data-answer-close]')?.forEach(x=>x.addEventListener('click',()=>$('answerDetailModal')?.classList.add('hidden')));
 $('exportAnswersBtn')?.addEventListener('click',exportAnswers);
 $('answersNewBtn')?.addEventListener('click',()=>modal(true));
 $('questionsNewBtn')?.addEventListener('click',()=>modal(true));
 $('settingDark')?.addEventListener('change',e=>{localStorage.setItem('costalogTheme',e.target.checked?'dark':'light');theme()});
 $('settingAuto')?.addEventListener('change',e=>localStorage.setItem('costalogAutoRefresh',e.target.checked?'1':'0'));
 $('settingAnti')?.addEventListener('change',e=>localStorage.setItem('costalogAlertAnti',e.target.checked?'1':'0'));
 $('settingVolume')?.addEventListener('change',e=>localStorage.setItem('costalogAlertVolume',e.target.checked?'1':'0'));
 $('clearLocalBtn')?.addEventListener('click',()=>{if(confirm('Remover somente os registros criados neste navegador?')){localStorage.removeItem('costalogAbastecimentos');load()}});
}
function renderSettings(){const r=$('settingsRecords');if(r)r.textContent=fmt(allRows.length);const d=$('settingDark');if(d)d.checked=document.body.classList.contains('dark-mode');const a=$('settingAuto');if(a)a.checked=localStorage.getItem('costalogAutoRefresh')!=='0';const an=$('settingAnti');if(an)an.checked=localStorage.getItem('costalogAlertAnti')!=='0';const vo=$('settingVolume');if(vo)vo.checked=localStorage.getItem('costalogAlertVolume')!=='0'}
const originalView=view;
view=function(v){originalView(v);if(v==='settings')renderSettings();if(v==='questions')renderQuestions()};
setupExtraPages();

$('entryPlate')?.addEventListener('input',()=>{const i=$('entryPlate');i.value=i.value.toUpperCase().replace(/[ -]/g,'');updatePlateAutomation();updateOdoAutomation()});
$('entryOdo')?.addEventListener('input',updateOdoAutomation);
$('entryLiters')?.addEventListener('input',updateLitersAutomation);
$('setDateBtn')?.addEventListener('click',()=>showEntryValidation('✓ Data definida para '+br($('entryDate').value)+'.','ok'));
$('entryDate')?.addEventListener('change',()=>showEntryValidation('Data selecionada: '+br($('entryDate').value)+'. Clique em “Definir” para confirmar.','ok'));
previewPhoto('entryPhotoPlate','photoPlatePreview');previewPhoto('entryPhotoOdo','photoOdoPreview');previewPhoto('entryPhotoPump','photoPumpPreview');
